name: Check Build

on: [pull_request]

jobs:
  build:

    strategy:
      matrix:
        php: ["7.4", "8.0"]

    runs-on: ubuntu-latest
    container:
      image: eventjet/checks-${{ matrix.php }}:latest

    env:
      COMPOSER_ARGS: ''

    steps:
      - name: Checkout
        uses: actions/checkout@v2

      - name: Prepare environment
        run: |
          mkdir -p /root/.ssh
          ssh-keyscan -t rsa github.com >> /root/.ssh/known_hosts

      - name: Ignore Plaform Reqs if on PHP8
        if: ${{ matrix.php == '8.0' }}
        run: echo "COMPOSER_ARGS=--ignore-platform-reqs" >> $GITHUB_ENV

      - name: Composer Cache
        uses: actions/cache@v2
        with:
          path: $(composer config cache-files-dir)
          key: ${{ runner.os }}-composer-${{ hashFiles('**/composer.json') }}
          restore-keys: |
            ${{ runner.os }}-composer-

      - name: Install dependencies
        run: |
          composer install --no-progress --no-suggest --no-interaction ${{ env.COMPOSER_ARGS }} > /dev/null

      - name: Static analysis
        run: |
          composer check-deps
          composer cs-check
          composer phpstan -- --no-progress
          composer psalm

      - name: Tests
        run: |
          vendor/bin/phpunit --coverage-clover=coverage.xml --stop-on-failure
          composer run --timeout=0 infection

      - name: Log Infection mutants
        run: |
          git fetch --depth=1 origin $GITHUB_BASE_REF
          composer run --timeout=0 infection -- --logger-github --git-diff-filter=AM --git-diff-base=origin/$GITHUB_BASE_REF

      - name: Monitor coverage
        if: github.event_name == 'pull_request'
        uses: slavcodev/coverage-monitor-action@v1
        with:
          github_token: ${{ secrets.GITHUB_TOKEN }}
          clover_file: "coverage.xml"
          threshold_alert: 99
          threshold_warning: 99
